server:
  port: 8090

spring:
  application:
    name: order-taking-api

  datasource:
    url: jdbc:mysql://localhost:3306/melita
    username: root
    password: Chiziterealaoma7
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    addresses: localhost:5672

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


