server:
  port: 8020

spring:
  application:
    name: order-approval-api

  datasource:
    url: jdbc:mysql://localhost:3306/melita-order-approval
    username: root
    password: Chiziterealaoma7
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    addresses: localhost:5672

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



