server:
  port: 8080

spring:
  application:
    name: order-taking-api

  datasource:
    url:
    username:
    password:
    driver-class-name:

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka